### ISSUE TITLE
News Items Titles are too long

### ISSUE THREAD

**Issue by shaulhadar** [framework7io/framework7-plugin-feeds#1]
Hi Vlad, I am working on implementing your new feed plugin. I didn't succeed yet, but when checking the plugin's demo on the idangerous framework 7 page, i noticed that when you go inside a news item, the title is too long, and overlabs the "Back" button text.  
Is there any way to adjust this perhaps?

Thanks..

**Comment by nolimits4web** [comment]
> overlabs the "Back" button text

It should be ok, such issue could be in recently released 0.9.9 but fixed in 0.10.0 so make sure that you have cleared cache

It should like on this screenshot:
![long title](https://cloud.githubusercontent.com/assets/999588/5354517/4a5f8788-7f9a-11e4-8c21-4a38ce4203c5.png)
