### ISSUE TITLE
How to get unread item count and highlight unread items?

### ISSUE THREAD

**Issue by wickyhu** [framework7io/framework7-plugin-feeds#3]
Hi,

The plugin is easy to use.

Is it possible to get unread item count and highlight (bold or colored) unread items?

Thanks
Wicky

**Comment by nolimits4web** [comment]
Yes, it is possible, but it should be totally custom soultion. You need to store somewhere (for example in localStorage) read/unread flag and display it using custom templates.

**Comment by wickyhu** [comment]
Thank you!
