### ISSUE TITLE
howto correctly install the plugin-feeds in the template project?

### ISSUE THREAD

**Issue by stereo3d** [framework7io/framework7-plugin-feeds#9]
After plenty of tries, I need your help. 
I am not getting this plugin to work in the structure of the template project
which is different from the example here on github.

I created a Framework7 template project using:

framework7 create --ui
I selected cordova + pwa as target with recommended settings.

npm install
npm install framework7-plugin-feeds
where is the correct folder to add the plugin code.
I work in the “src” folder.

I install CSS and JS SCRIPT in the index page

However I cannot get the plugin to work.
I copy the sample demo code in my project but I only get an endless spinning wheel.
I am not sure the plugin is really active.
page suffixes are .f7 instead of html as in the sample demo code.

I would be very grateful for a help how to integrate the demo code properly in the template project generated by framework7 create --ui

sincerely thanks

**Comment by nolimits4web** [comment]
Hey, there was a Feeds plugin update today with support for framework7 v6
